### ISSUE TITLE
Unnecessary sidebars with displayed values from the graph

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#377]
After hovering over the charts in the dashboard, the data window has redundant scrollbars
![image](https://user-images.githubusercontent.com/48470313/100200412-d977a580-2efe-11eb-84a5-83682fd0d9a3.png)

**Comment by wu-sheng** [comment]
I am not sure whether this is from ECharts, @Fine0830 @Jtrust when you have time, please take a look.

**Comment by Jtrust** [comment]
![image](https://user-images.githubusercontent.com/21056967/100268267-b47f4300-2f8f-11eb-9a55-98b138c4f436.png)
This is what it looks like on a macbook. Scrollbars appear on Windows because we set echarts configured `extraCssText: 'max-height: 300px; overflow: scroll; '` to limit the display area when there is too much content.

**Comment by Fine0830** [comment]
Will set the config on my computer, the issue is reappeared.
![123](https://user-images.githubusercontent.com/20871783/101115117-c90dac00-361d-11eb-9a39-85c771a60a69.png)
